services:
  - type: web
    name: estoque-pronta-entrega
    env: python
    buildCommand: |
      pip install -r requirements.txt
      git lfs install
      git lfs pull
    startCommand: python app.py
    plan: free
    envVars:
      - key: PORT
        value: 10000

